### ISSUE TITLE
Issues with webkit2gtk

### ISSUE THREAD

**Issue by okraits** [vain/lariza#11]
I have strange issues with lariza/webkit2gtk:

- When i visit https://github.com/, i get a black flickering, after ~ 10 seconds, it is gone. This happens with other webpages, too.
- When i visit https://www.google.de/maps, i get a black screen.

I experienced these issues both with your code as well as with my master branch (now on webkit2gtk as well).
With webkitgtk2, i don't have these issues.

Can you reproduce these?

Versions:

webkit2gtk 2.6.4-1
webkitgtk2 2.4.7-1

Note: i only tested this on i686 so far.

**Comment by vain** [comment]
Huh, no, I can’t reproduce that. :-(

Can you add more details about your system? What distro are you using, kernel version, what’s your GPU, are you using a compositor, what acceleration method are you using (SNA, EXA, UXA,  ...), what’s your GTK3 theme, … stuff like that.

I assume this is not related to tabbed because you’re usually not using it, right?

**Comment by okraits** [comment]
Distro is Arch Linux, kernel is 3.17.6-1-ARCH, GPU is Intel 855GM with xf86-video-intel 2.99.917-1, no compositor, gtk3 theme is Adwaita.

Changing the accel method from SNA to UXA removed the flickering on github, but after login to github, clicking the link to this issue brought me back to the not-logged-in startpage of github. Google Maps still gives me a black screen (webview).

**Comment by vain** [comment]
Usually, I’d suggest trying another WebKit2 browser to see if you can reproduce the errors there. But since there are almost none, that’s kind of a problem. You could try epiphany if you’re willing to pull all those dependencies.

What worries me, though, is that you’re having problems logging in to GitHub. This is most certainly not related to any GPU driver issues. Are you using the adblock extension?

**Comment by okraits** [comment]
I just checked again and logging in to github works again, Google Maps doesn't though. Very strange.

I must say that i'm not very confident about the future of webkit(2)gtk :(

**Comment by okraits** [comment]
I stopped trying to fix this issue. So i'll close it.

I started implementing a successor of lariza with Qt Webkit: https://github.com/okraits/breasy
I have the impression that Qt Webkit is more stable than webkit2gtk (i don't have the issue described here with Qt Webkit) and very fast.
Additionally, Qt has a nice API and good documentation. And i can migrate to the chromium engine if i want to.
