### ISSUE TITLE
Concern about /tmp as default Download storage directory

### ISSUE THREAD

**Issue by Narrat** [vain/lariza#13]
Dunno how many distros switched to /tmp-on-tmpfs[0], but since Arch and Fedora adopted this it should be quite a few (all that are based on those). Dunno about Debian.

So, if someone is using the default environment variables of Lariza he could run into problems if he downloads some files (if the accumulated size exceeds RAM/2).
Also if he doesn't save/move the downloaded files and a reboot occurs which results in files lost.

So for large temporary files and old /tmp behaviour it's suggested to use /var/tmp and in my opinion this should be the default Download dir.
______
[0] https://fedoraproject.org/wiki/Features/tmp-on-tmpfs

**Comment by vain** [comment]
Hi,

I explicitly chose /tmp because it's volatile on modern systems. I want my downloads gone when I reboot the system. I also do most of my other work in /tmp and I only move those files back to my hard drive that I really want to keep. This is a simple way to avoid cluttering your home directory or hard drive with unimportant stuff.

But, well, that's *my* approach and I do realize that it might not work for other people.

Is /var/tmp a better choice? I think, a user would most likely expect lariza to use $XDG_DOWNLOAD_DIR or maybe the home directory. Sadly, it appears that you need to explicitly configure `xdg-user-dirs` for the GLib function `g_get_user_special_dir()` to work (i.e., create ~/.config/user-dirs.* -- if those don't exist, then GLib simply returns NULL). I really doubt that "suckless users" have done this (I haven't). As a result, lariza can't rely on `g_get_user_special_dir()` and I would need to implement some kind of fallback mechanism which chooses another directory that is guaranteed to exist. Using the home directory as a fallback sucks (see [this discussion](http://lists.suckless.org/dev/1501/25063.html)). Using ~/Downloads sucks, too, because it's not guaranteed to exist (or maybe it does exist but with a locale-dependant name or whatever).

Hence, /var/tmp is indeed a valid choice. It's guaranteed to exist, it's persistent and it won't trigger the OOM killer.

If a user really wants to use XDG directories, he can still do so by setting `LARIZA_DOWNLOAD_DIR=$(xdg-user-dir DOWNLOAD)`.

Cheers!

**Comment by Narrat** [comment]
>I think, a user would most likely expect lariza to use $XDG_DOWNLOAD_DIR or maybe the home directory.

Yeah, I assumed that as well, when I downloaded some files and checked the $XDG_DOWNLOAD_DIR and found nothing :D Luckily something that could be solved by looking into the README.
And I thought you had a reason for using /tmp and the replacement should be a comparable replacement (although it's not so volatile as tmpfs) but a usable one if someone is using a machine with low RAM.
