### ISSUE TITLE
Add new control binding for history browsing

### ISSUE THREAD

**Issue by milouse** [vain/lariza#16]
... because not everybody has a full featured mouse :)

More seriously, as Mod1-n are already taken by search related feature, I propose the following key bindings:

- unmap `Mod1 + n` from search browsing
- map `F3` as search next and `F2` as search previous (which are handy for left hand)
- `Mod1 + n` is now used to advance in browsing history if we previously go back 
- `Mod1 + p` is used to go back in history

What do you think about it?

By the way, I'm discovering your work and as it seems well documented I'll try to implement it my self and, if you agree my proposal, send you a pull request.

**Comment by vain** [comment]
I agree that it's a little annoying to not have those hotkeys without having a "high end" mouse. :-) On my laptop, I usually use the context menu (right mouse click) and choose "backward".

How about the opposite, though? Keeping `Mod1 + *` and use `F2`/`F3` for backward and forward? I think those two buttons are easier to reach than `Mod1 + n`/`Mod1 + p`, plus you can hit them with *one* hand. The `Mod1 + *` combinations would require you to either stretch your left hand quite a bit or to move your right hand from the mouse to the keyboard. I don't think that's optimal.

And, yeah, sure, a pull request is very appreciated. :-)

**Comment by milouse** [comment]
We are all the little slaves of our (bad?) habits... My proposal around F3 for search comes from the default keybindings in Firefox. Thus it's easier for me to remember that F3 is for search and n/p for history browsing. On the other hand, your argument is valid too.

I don't know if you took the time to check, but I've created my own distinct branch in order to test various stuff. In fact I use a [bépo](http://bepo.fr/wiki/Accueil) (fr) keyboard and so, your default configuration for both hand do not always match at is best for me.

Thus, I'll certainly push a PR with F2/F3 for history to keep the spirit of your own project. If other ideas come, I'll let you know. Do not hesitate to reclaim a PR if you see some good ideas in my ugly branch :)

**Comment by vain** [comment]
I see, bépo is indeed not very compatible with the default bindings. I guess a lot of other layouts aren't either. And I'm also pretty sure that a left-handed person will certainly not like the default bindings. :(

I think there's only one reasonable option, even though it might sound selfish at first: lariza (at least *my* branch of it) should come with key bindings that fit my workflow/habits. Other users can customize their keys by editing the source code.

Of course, it would be easier if there was a config file or a GUI to do so. However, lariza aims at "competent power users" who are very well capable of editing C code. Just like you and some others did. :)

Now, for key bindings to be *customizable*, they have to exist in the first place. Plus, in general, I think that forward/backward keys are useful. That's why I cherry-picked your commit c3cd6465b45b44690ec6f24f27437867e59b0e3d, so authorship/credits are properly assigned to you. I edited it, though, so that F2/F3 go backward/forward.

**Comment by milouse** [comment]
Cherry pick, the one thing I have to masterize some day... I'm pleased if you found something useful in my work. And as I said, I totally agree your vision on the selfish mode of dev: that's why I maintain my own branch with _my_ custom bindings and feature set. Have a good day.
