### ISSUE TITLE
Can't plug-in to XID xxxxxxxx

### ISSUE THREAD

**Issue by benjaminrich** [vain/lariza#21]
I'm getting the error:

    lariza: Can't plug-in to XID 12582915.

I browsed the code and I see where it comes from, but I don't understand enough to know how to fix it. I installed from AUR on arch, and I installed tabbed as well.

**Comment by vain** [comment]
Let's gather some more information:

-   How do you launch lariza? A simple `lariza`?
-   You do use X11, do you? (I vaguely remember that current versions of GNOME default to Wayland or something along these lines.)
-   Does `tabbed xterm -into` work? An instance of tabbed with XTerm embedded into it should appear.
-   What's the output of `ps aux | grep tabbed`?
-   What's the output of `xprop -id 1234` (where 1234 is the ID of the error message)?

**Comment by benjaminrich** [comment]
Thanks for the quick response. 

- I just ran the command `lariza`.
- I am in fact on GNOME (3.22.2), but I don't know if it is Wayland or not.
- `tabbed xterm -into` works.
- Output of `ps aux | grep tabbed`

    [ben@elx2 ~]$ ps aux | grep tabbed
    ben       5280  0.0  0.0  18920   308 pts/0    S+   16:03   0:00 tabbed -c -d -p s1 -n lariza
    ben       7412  0.0  0.0  11976  2328 pts/1    S+   16:11   0:00 grep tabbed
    [ben@elx2 ~]$

- output of `xprop -id 12582915`:

    [ben@elx2 ~]$ xprop -id 12582915
    _NET_WM_STATE(ATOM) = 
    WM_STATE(WM_STATE):
    		window state: Normal
    		icon window: 0x0
    _NET_WM_DESKTOP(CARDINAL) = 0
    _NET_FRAME_EXTENTS(CARDINAL) = 0, 0, 37, 0
    _NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_MOVE, _NET_WM_ACTION_RESIZE, _NET_WM_ACTION_FULLSCREEN, _NET_WM_ACTION_MINIMIZE, _NET_WM_ACTION_SHADE, _NET_WM_ACTION_MAXIMIZE_HORZ, _NET_WM_ACTION_MAXIMIZE_VERT, _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_CLOSE, _NET_WM_ACTION_ABOVE, _NET_WM_ACTION_BELOW
    WM_NAME(COMPOUND_TEXT) = "tabbed-0.6 ::"
    _NET_WM_NAME(COMPOUND_TEXT) = 0x74, 0x61, 0x62, 0x62, 0x65, 0x64, 0x2d, 0x30, 0x2e, 0x36, 0x20, 0x3a, 0x3a
    WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW
    WM_LOCALE_NAME(STRING) = "en_CA.UTF-8"
    WM_NORMAL_HINTS(WM_SIZE_HINTS):
    		program specified size: 800 by 600
    WM_CLIENT_MACHINE(STRING) = "elx2"
    WM_CLASS(STRING) = "lariza", "tabbed"

**Comment by vain** [comment]
Okay, what you posted does not indicate any obvious error. I'll have to try to reproduce this myself. Probably the upcoming weekend.

In the meantime, according to [stackexchange](http://unix.stackexchange.com/questions/202891/how-to-know-whether-wayland-or-x11-is-being-used), you could run the following to see if you're using wayland:

    ps aux | grep gnome-shell

**Comment by vain** [comment]
I set up a basic GNOME installation on Arch Linux. I can reproduce your error.

As suspected, GNOME runs on Wayland by default these days, as can be seen by running `ps aux | grep -i way`. They still use [XWayland](https://wayland.freedesktop.org/xserver.html) to ensure some kind of compatibility between "old" X11 applications and newer applications that support wayland.

However, this setup appears to break lariza. I think lariza itself runs natively on Wayland because it's a GTK+ application. tabbed, on the other hand, surely has no support for Wayland whatsoever.

One workaround that appears to work is to make lariza use X11 again by setting the environment variable `GDK_BACKEND=x11`. At the shell, you can do this:

    $ GDK_BACKEND=x11 lariza

This only sets the variable for lariza and all other applications are unaffected. If this works for you, you might want to write a little wrapper script.

Now, this might be a short term solution. I don't know about the future plans of the GNOME guys and GTK+ guys. Will `GDK_BACKEND=x11` still work in two years? We'll see.

**Comment by benjaminrich** [comment]
Works for me. Thanks.
