### ISSUE TITLE
Opening New Window Does Not Place Cursor in Address Field

### ISSUE THREAD

**Issue by githububub** [vain/lariza#22]
1. Opening a new window `MOD1+e` must be followed by a second keypress combo `MOD1+l` before the address field becomes usable.

2.  Opening a new window results in a window populated with either `about:blank` or a preconfigured home page. Moving the mouse pointer (instead of a key combo) into the address field requires the existing URI to be highlighted before being overwritten.

A better way would be to open a new window with the cursor in a blank address field to accept immediate paste/text input. Regardless, great job on this browser. Please consider adding support for a user and/or a customizable night mode style sheet. I can live without everything else (though the ability to toggle javascript and local storage would be nice). When I am working on a website within a dark themed IDE late at night, launching lariza absolutely destroys my eyesight (even with the monitor brightness all the way down). Again, great job so far nonetheless :)

**Comment by vain** [comment]
The typical workflow is to use a "start page", i.e. a static HTML page that contains links to your most frequently visitied web sites ([for example](https://nixers.net/showthread.php?tid=1856)). That's the page opened by `Mod1+e`. The start page is often crucial, so it's always opened.

I'm not so sure if placing the cursor into an empty input box is easy to accomplish. See, when we open a new window using `Mod1+e`, we always load some page, even if it is `about:blank`. This triggers a whole lot of events. At some point, page load is complete and this event sets the input box to the address of the page -- overwriting everything that's in there.

I'll have to think about that.

By the way, I have a global system hotkey that opens the content of the clipboard in a new browser tab. This way, I don't even need to open a new tab manually and then paste the URL. Maybe this workaround could work for you as well. (Although I don't consider this a workaround -- I've used this hotkey long before I wrote lariza.)

Custom CSS is probably unlikely to happen since I, personally, have no need for it whatsoever. :/ This would result in unmaintained code which is a bad thing. I'll look into it anyway -- maybe it's really easy to implement/activate.

Same goes for toggling JS. I've long given up on maintaining long lists of web sites where JS is OK and where it's not. The WWW is a mess. WebKit is not an extremely secure library either, so if you're concerned about security, you might want to consider other options. :/

**Comment by githububub** [comment]
Thanks for considering the enhancements.

**Comment by vain** [comment]
Mhh, the only way to reliably position the cursor into an empty input box when opening new windows is to open *no URI* whatsoever. This opens up a can of worms and many corner cases that the current code does not expect. (Plus, I, personally, would not use lariza that way which means all the new code would be barely tested.)

As for user CSS, I'll keep this on my TODO list or "to try" list (although still unlikely to happen). As suspected, this would require a lot of new code/logic and maybe even a config file.

I hate to turn down people who are willing to participate, but I don't think I'll implement those changes. Sorry.
