### ISSUE TITLE
[feature] option to open link with

### ISSUE THREAD

**Issue by Docbroke** [vain/lariza#25]
This option is there in w3m, where link-under-cursor or page-url can be opened with external program. 

It will help in things like opening youtube link with mpv or downloading with curl or opening torrent link with transmission-cli/deluge, or sometimes opening webpage with other browser like chromium/firefox in case there are issues with webkit2 on that page.

This involves only feeding link to selected external program so it should not be a huge coding work, but functions of the browser can be greatly enhanced.

**Comment by vain** [comment]
Yes, IIRC, this has been brought up before. Ideally, there would be an sxiv-like key handler, i.e. a user supplied shell script. This would keep the code in lariza relatively short, but would add a great deal of flexibility.

Maybe something like this:

-   Ctrl+X, $key, $click_on_link: Opens the link via the key handler.
-   Ctrl+C, $key: Opens the current URI via the key handler.

It would even be possible to use the same key handler script for both actions, since it would be called like `key_handler.sh ^X g gopher://floodgap.com` or `key_handler.sh ^C f https://github.com`.

Something along these lines. I like that idea. I think I'll play with that in the next few days.

**Comment by Docbroke** [comment]
I am glad that you liked the idea. I haven't used sxiv, but it appears similar to what is there in w3m.  We can also make use of our location bar (just like current Alt+k),

- Alt+C (location bar focused and empty), c (#input c in location bar, c=key defined in shell script as "$TERM -e curl")
link opens with curl
- Alt+C, firefox (#key not defined in shell script)
link opens with firefox

Same way with Alt+x for clicked links.

BTW: I read your idea of having keyboard key bound to open lariza with PRIMARY, I liked that and implemented by binding "winkey+o" to `lariza $( xclip -o)`. I have also created bookmarking/searching script usable with any browser if you like to look at that https://github.com/Docbroke/w3m-dmenu/blob/master/dmenu-browse

>

**Comment by vain** [comment]
I've pushed an early draft on the branch `dev-external-handler`. Also see my commit message. Let's play with this for a while.

To understand how/when the handler is invoked, start with this simple script:

    #!/bin/sh
    
    for i
    do
        echo "'$i'"
    done

`?foobar` and then clicking a link feels weird. Ideally, WebKit's context menu should be extended to include a new item: "Launch in external handler". So, the user would do a right-click on a link, chose that option, then input jumps to the location bar, and -- after the user hits enter -- the handler will be invoked.

I don't know how much work it is to extend this menu, though. Will have to investigate.

**Comment by Docbroke** [comment]
I changed config.c in my downloaded lariza file with config.c from new branch, compiled and installed lariza. Created "lariza-external-handler" in path. But when i input !foobar lariza tries to open `http://!foobar/` with not found error.

**Comment by vain** [comment]
`config.c`? You need to do the following:

    $ cd ~/git
    $ git clone https://github.com/vain/lariza.git
    $ cd lariza/
    $ git checkout origin/dev-external-handler
    $ make

You also have to make sure that the new script is available in your `$PATH`. As a first step, you create the script:

    $ cd ~/git/lariza
    $ vim lariza-external-handler
    $ chmod +x lariza-external-handler 

You can then run lariza from within that directory, e.g.:

    $ cd ~/git/lariza
    $ PATH=$PATH:. ./lariza -C

I'm using `-C` here to avoid communication with any other running instance.

**Comment by Docbroke** [comment]
thanks, I thought only changed file is config.c so I can recompile after changing that file but I was wrong.

Now, I played with this new feature a bit, issue with current script is it echo's both "!foobar" and "$url", so I did some modifications.

`#!/bin/bash

TERM=sakura

case "$1" in

!vim|?vim) $TERM -e vim $2 ;;
!chromium|?chromium) chromium $2 ;;
!w3m|?w3m) $TERM -e w3m $2 ;;
!curl|?curl) $TERM -e curl $2 ;;

*) echo "unknown input" ;;

esac`

Now "!chromium" shall open current url in chromium.  The issue with using ?chromium is once we click on any link in the page the link is not forwarded to the lariza-external-handler but the page url is forwarded, so inplace of the clicked link page-url is opened ( so basically ! and ? opens the same page url, but ? works after clicking somewhere) I guess there is something wrong in the commit where we need to tell lariza that when keyword ? is used it has to forward clicked link and not the current page-url.

**Comment by vain** [comment]
Whoops, you're right. That `?` issue was a mistake on my part. I pushed a fix on the branch `dev-external-handler`.

**Comment by Docbroke** [comment]
BINGO! this works great now, I just tried playing few youtube videos with mpv.

**Comment by Docbroke** [comment]
Here is update to dev-external-handler
`#!/bin/bash

TERM=sakura

case $1 in

!w3m|?w3m) $TERM -e w3m $2 ;;
!mpv|?mpv) $TERM -e mpv $2 ;;
!ytdl|?ytdl) $TERM -e youtube-dl $2 ;;
!trans|?trans) $TERM -e transmission-remote-cli $2 ;;
!*) x="$(echo $1 | awk -F! '{ print $2 }')" && $x $2 ;;
?*) x="$(echo $1 | awk -F? '{ print $2 }')" && $x $2 ;;

esac`

**Comment by vain** [comment]
By the way, if not quoted, the "labels" in a `case` are patterns. This means,

    case $1 in
        ?w3m) ... ;;
    esac

will catch both `!w3m` and `?w3m`. If you want to catch a literal `?w3m`, you would have to use:

    case $1 in
        '?w3m') ... ;;
    esac

**Comment by Docbroke** [comment]
Thanks for bringing that insight. As I don't need to literally catch "?", I use that insight to cut-short the script. Updated in previous comment.

**Comment by Docbroke** [comment]
After playing for a while, I feel we need two more shortcuts
`Alt+? focus location bar with input ?` and Alt+! in similar way. As current workflow needs Alt+l followed by either ? or ! berfore putting keyword

**Comment by vain** [comment]
Yeah, probably. `Alt+?` and `Alt+!` are very awkward on a german keyboard, though.

I'd still like to edit the context menu, as outlined above. I'll probably investigate that this weekend.

**Comment by Steef435** [comment]
Hey there, great project you haver here! I especially like how simple the adblocker is, I'll be using that if I ever get back to my WebKit Frankenstein project.

Fiddling with the context menu is rather easy, here are some pointers:
- Connect to the context-menu signal of a WebView: https://webkitgtk.org/reference/webkit2gtk/stable/WebKitWebView.html#WebKitWebView-context-menu
- Check whether the HitTestResult provided is a link (webkit_hit_test_result_context_is_link)
- Add a ContextMenuItem using [webkit-context-menu-append](https://webkitgtk.org/reference/webkit2gtk/stable/WebKitContextMenu.html#webkit-context-menu-append)

You'll need to use GtkAction for the item though, not sure how much lines of code that will end up consuming, never used it.

I haven't written C for a year (and I'm a newbie anyway) but I wouldn't mind giving it a shot in about 24 hours if you don't feel like picking it up yourself.

(In case you're wondering, Docbroke's screenshot on the Arch wiki brought me here)

**Comment by vain** [comment]
@Steef435 Thank you, that's very helpful! I'll give it a shot. :-)

(Meh, WebKit2 uses GtkAction which has been deprecated since Gtk 3.10. This means we're stuck with an annoying deprecation warning. I don't think we can do anything here, though.)

**Comment by vain** [comment]
I've pushed the changes to the branch `dev-external-handler`. It now works like this:

-   Enter `!foo` in the location bar to launch the current URI in the external handler.
-   Right click on a link, image or "media" and select "Open in external handler". The input bar will now be focused and set to `?`. You can now enter `?foo` to open the previously selected URI in the external handler.

---------------------

By the way, I can think of a completely different implementation to solve the issue at hand. If there was a hotkey to copy the current URI to the clipboard, one could do this:

-   `<copy current URI to clipboard>`, followed by some generic system hotkey (for example, something managed by sxhkd) which runs the external handler. It would require a little more logic in said handler, for example it could launch dmenu to allow you to enter `yt` or `curl` or whatever. The handler would then just read the URI from the clipboard.
-   You can already copy link and image URIs using WebKit's standard context menus. Again, after that, launch the external handler using a system hotkey.

This would require *a lot* less code in lariza while still allowing you to do the same thing. But, of course, the external handler would be more complex, so there's the trade-off.

Fun thing is, you can already do this by just hitting `Alt+l` followed by `Strg+C` followed by the system hotkey.

To be honest, I'm inclined to optimize *this* workflow rather than to put more code into the browser. It's much more UNIX-y. On the other hand, it feels a little more "clunky".

Let me know what you think.

**Comment by Docbroke** [comment]
I liked the idea of using dmenu, and I created a script for testing. This method shall work with any browser.
```
#!/bin/bash

TERM=sakura
shopt -s lastpipe
xclip -o | /usr/bin/dmenu -l 1 | read -a "url"

case "${url[@]:1}" in

w|w3m) $TERM -e w3m "${url[@]:0}" ;;
m|mpv) $TERM -e w3mpv "${url[@]:0}" ;;
M|MPV) $TERM -e mpv "${url[@]:0}" ;;
y|ytdl) $TERM -e w3ytdl "${url[@]:0}" ;;
Y|YTDL) $TERM -e youtube-dl "${url[@]:0}" ;;
## download torrent using transmission-cli
t|torrent|transmission|trans) $TERM -e transmission-remote-cli "${url[@]:0}" ;;
## downlod with curl in current dir (home)
d) $TERM -e curl -L -O --user-agent Mozilla/5.0 "${url[@]:0}" ;;
## save page as curl.html in Downloads
s) $TERM -e curl -L -o ~/Downloads/curl.html --user-agent Mozilla/5.0 "${url[@]:0}" ;;
## save full page with wget, saved in Downloads
wget) $TERM -e wget --user-agent=Mozilla/5.0 --mirror -p --convert-links -P ~/Downloads "${url[@]:0}" ;;
## use any other external program with !chromium or !firefox or ?firefox etc.
*) "${url[@]:1}" "${url[@]:0}" ;;

esac
```
However workflow is not very smooth.
1. copy the url
2. open the script with hotkey
3. select the url with "tab", so that url is copied to text input
4. input keyword after the url (with a space between them), like "$url mpv"
5. url opens with mpv/selected keyword

The issue is url is not autoselected in dmenu so there is one extra step. I think our current method of using !/? is better.

**Comment by Docbroke** [comment]
here is an update, I think this is working nice, I will try this for a while to see how it goes

'''
#!/bin/bash

TERM=sakura
shopt -s lastpipe

# xclip -o | /usr/bin/dmenu -l 1 -fn "Inconsolata 12" | read -a "url"
echo -e "w3m\nmpv\nMPV\nyoutube-dl\nYOUTUBE-DL\ntransmission\ncurl-download\ncurl-save\nwget-saveall" | /usr/bin/dmenu -l 10 -fn "Inconsolata 12" | read "option"

case $option in

# case "${url[@]:1}" in


w3m) $TERM -e w3m "$(xclip -o)" ;;
mpv) $TERM -e w3mpv "$(xclip -o)" ;;
MPV) $TERM -e mpv "$(xclip -o)"  ;;
youtube-dl) $TERM -e w3ytdl "$(xclip -o)" ;;
YOUTUBE-DL) $TERM -e youtube-dl "$(xclip -o)" ;;
## download torrent using transmission-cli
transmission) $TERM -e transmission-remote-cli "$(xclip -o)" ;;
## downlod with curl in current dir (home)
curl-download) $TERM -e curl -L -O --user-agent Mozilla/5.0 "$(xclip -o)" ;;
## save page as curl.html in Downloads
curl-save) $TERM -e curl -L -o ~/Downloads/curl.html --user-agent Mozilla/5.0 "$(xclip -o)" ;;
## save full page with wget, saved in Downloads
wget-saveall) $TERM -e wget --user-agent=Mozilla/5.0 --mirror -p --convert-links -P ~/Downloads "$(xclip -o)" ;;
## use any other external program with !chromium or !firefox or ?firefox etc.
*) "$option" "$(xclip -o)" ;;
esac
```
try this and let's see how it goes

**Comment by Docbroke** [comment]
Alright, after giving this a good night's sleep, I have an idea that should work.

What we need to do is rollback all the changes or create a new branch with following changes,
1. "new keyboarc shortcut" - when clicked, current url is copied to clilpboard and the link_handler script is executed
2. in right click context menu add option to "open with link_handler", which on  selecting copies the clicked url to clipboard and simple executes the link_handler
3. In any case link_handler script as posted above with get the url from clipboard and gives option to choose how to open that link through dmenu frontend.

I think this is the best worflow, and it is more UNIX-y, too.

**Comment by vain** [comment]
I think that will work, with one adjustment: The URI should be passed to the handler by setting a command line argument. For example:

    lariza-external-handler -u https://github.com

*Forcing* the handler to read the clipboard doesn't feel right. It's simple to implement using command line arguments and, most importantly, it doesn't "clobber" (i.e., overwrite without asking) the current contents of the clipboard. The link handler can still optionally read the/a clipboard if no `-u` is present.

(By the way, `lariza-external-handler` will be a hardcoded string. I think that's okay because users can easily set up a symlink or wrapper script or whatever.)

I pushed this implementation to the branch `dev-external-handler`. I'll eventually clean up that branch (and add documentation).

**Comment by Docbroke** [comment]
This is going great. Not forcing the clipboard is also a good idea. I have already dug through code and found out hotkey ( though I'm totaly illiterate in 'c'). 
And yes, here is my updated script,
https://github.com/Docbroke/link_handler/blob/master/lariza-external-handler

**Comment by vain** [comment]
Just for reference, that's the script I use: https://github.com/vain/bin-pub/blob/master/browser-link-handler

**Comment by Docbroke** [comment]
I recently realized that we can use lariza-external-handler to add bookmarks, also. So I did update my my script https://github.com/Docbroke/link_handler/blob/master/lariza-external-handler and my bookmark manager script https://github.com/Docbroke/w3m-dmenu/blob/master/dmenu-browse, accordingly.

Btw, you can use rofi in place of dmenu with some added features like "-msg "open $1 with" will display your message in lower line so that you can avoid `$uri_short` in your script

**Comment by vain** [comment]
There's all sorts of things you could do with that handler. For example, you could implement a password manager: Hit `Alt+x`, pass the URI to a simple password manager which then types user credentials using xte/xdotool.

I also like that I know have an easy way to open Gopher "URLs" from within lariza. :-)

I'll clean up and merge the extra branch in a moment.
