### ISSUE TITLE
U2F Integration

### ISSUE THREAD

**Issue by beli3ver** [vain/lariza#31]
Hello,

do you think about to integrate this standard

https://w3c.github.io/webauthn/#fido-u2f-attestation

Thanks?

**Comment by vain** [comment]
Not my field of expertise. I highly doubt that I'd implement this myself.

However, there's an ongoing discussion on the WebKit mailing list about U2F:

https://www.mail-archive.com/webkit-dev@lists.webkit.org/msg27077.html

Meaning, this should probably be implemented in the browser engine (WebKit) instead of a GUI frontend (lariza).
