### ISSUE TITLE
Searching with default search engine when host cannot resolved

### ISSUE THREAD

**Issue by notramo** [vain/lariza#33]
That would be good, if Lariza could search for the text with default search engine, when the text is not a URL. This can be done with one of these:
- the domain name doesn't contain at least one '.' chacacter
- the host cannot be resolved

**Comment by vain** [comment]
To be completely honest, I hate that feature in other browsers. :/

You can't get this right. There are too many corner cases where other browsers choose to ask a search engine instead of simply trying to open what I entered. For example, opening `router` is valid on my network. This fails in a default setup of either Firefox or Chromium. I have to turn that extra-intelligence *off* in other browsers and I like that I don't have to deal with things like that in lariza.

Plus, there is no signal in the webkit API to catch DNS failures. This means we would have to perform a manual DNS query before trying to load the page. Not that good. Even if there were such a signal, would it be a good idea to *always* ask the search engine in such events? What if you tried to open a "private URL with sensitive data"? What if it's an actual DNS failure and you can't reach the search engine either? Stuck in a loop.

I also fail to see the benefit in this feature. If you want to use a search engine, you can use keywords. Choose a one letter keyword, so it's very easy to explicitly state your intention to ask a search engine.

Sorry, won't implement. :/
