### ISSUE TITLE
Shortcut to hide location bar

### ISSUE THREAD

**Issue by notramo** [vain/lariza#34]
I often use Lariza in full screen. That would be good if Lariza has a shortcut to hide location bar.
That would be the best if it could show the bar when the cursor moves to the top of the screen (but with a shortcut to switch hide modes: never/cursor/always)

**Comment by vain** [comment]
Hmm, I'm not so sure about that. Sounds like a mostly cosmetic thing.

The implication is that you don't use tabbed? Because if you were using tabbed, you'd still see tabs even if there was no location bar. Or are you using a very small screen so you need to make good use of every pixel?

I, personally, probably wouldn't use this feature, so it would be unmanaged code. :/ A hotkey to simply hide the bar should be easy to implement. But the workflow wouldn't be very good. It would be much better if there was some kind of "auto-hide" feature, i.e. only show the bar if a user wants to enter something. And, as you suggested, ideally, moving the mouse cursor to the top of the window would reveal the bar as well. All that would be a lot of (unmanaged) code, though ...

**Comment by vain** [comment]
Closing, won't implement at the moment, see reasoning above. :/
