### ISSUE TITLE
Enable webgl

### ISSUE THREAD

**Issue by keze87** [vain/lariza#36]
(I'm not a dev)
```c
webkit_settings_set_enable_webgl(webkit_web_view_get_settings(WEBKIT_WEB_VIEW(c->web_view)),TRUE);
```
in
```c
WebKitWebView *
client_new(const gchar *uri, WebKitWebView *related_wv, gboolean show)
{
```
enables webgl.

Before vs After:

![2017-04-19-114753_1920x1080_scrot](https://cloud.githubusercontent.com/assets/9655998/25186291/24c011ce-24f6-11e7-80c0-a414bdea5275.png)

Thanks for your work!

**Comment by stefanhusmann** [comment]
In which line do you add that?

**Comment by keze87** [comment]
@stefanhusmann Before 231
```c
    clients++;

    //add
    webkit_settings_set_enable_webgl(webkit_web_view_get_settings(WEBKIT_WEB_VIEW(c->web_view)),TRUE);

    return WEBKIT_WEB_VIEW(c->web_view);
}
```

**Comment by vain** [comment]
I assume WebKit doesn't enable this feature by default because it's [considered experimental](https://webkitgtk.org/reference/webkit2gtk/2.14.5/WebKitSettings.html#WebKitSettings--enable-webgl):

> WebGL is an experimental proposal for allowing web pages to use OpenGL ES-like calls directly. The standard is currently a work-in-progress by the Khronos Group.

(I also guess that exposing your GPU like that could be a security nightmare.)

It would be interesting to play with this feature, though. Maybe I'll add an environment variable to enable it.

**Comment by stefanhusmann** [comment]
Thanks, but at least for me this cesiumjs causes the browser and after a while the whole computer to become unreponsive, and after another while the webpage crashes. At least not the whole computer crashes.
I am on Arch Linux with nouveau.

**Comment by vain** [comment]
WebGL can now be enabled:

    $ LARIZA_ENABLE_EXPERIMENTAL_WEBGL=1 lariza

It's still disabled by default. I'm on Arch Linux with an Intel HD 4000 and it works fine. But a) it's considered experimental by WebKit and b) even if it wasn't experimental, I'd leave it turned off by default because people should be *opting in* for a feature like this.

Have fun!

**Comment by keze87** [comment]
Thank you!

P.S. Would you consider adding smooth scrolling?

```C
webkit_settings_set_enable_smooth_scrolling(webkit_web_view_get_settings(WEBKIT_WEB_VIEW(c->web_view)),TRUE);
```

**Comment by vain** [comment]
I don't think so, sorry. :/ This is one of those very personal preferences. There are dozens options like that in WebKit and I don't plan to support them all in order to keep the code base slim.

(Enabling WebGL on the other hand adds a whole new set of functionality. It's not just a matter of taste. And, yeah, I do have some personal interest in playing with WebGL myself.)
