### ISSUE TITLE
Cursor doesn't change to "pointer" when hovering over links.

### ISSUE THREAD

**Issue by onodera-punpun** [vain/lariza#41]

**Comment by vain** [comment]
What window manager are you using?

I've seen this very often with early versions of katriawm. However, lariza wasn't the only "misbehaving" program back then. Especially, terminals using VTE were broken, too: Sometimes, you'd just get a hollow cursor (which normally indicates that the window does not have input focus) instead of a solid one.

Usage of tabbed seems to make things worse.

I haven't seen focus issues in lariza+katriawm in a long time. Plus, I've never seen them in Openbox. If I were to speculate, I'd say it's a window manager issue.

**Comment by onodera-punpun** [comment]
I'm using openbox. It does show the textbox cursor, just not the pointer one.

**Comment by vain** [comment]
Can you reproduce the problem when not using tabbed?

Oh and which version of tabbed are you using?

**Comment by onodera-punpun** [comment]
I'm using tabbed git master, with the following patch to center text and to make the bar a bit bigger, but I can't imagine that having any effect on the cursor: https://punpun.xyz/nfvh.patch

**Comment by vain** [comment]
Yes, if it also happens with `-T`, it's not a tabbed issue.

I'll see if I can reproduce this under Openbox.

**Comment by vain** [comment]
Hmm, works fine for me with Openbox. :/

When you hover over a link, does lariza show the URL of the link in its location bar?

**Comment by vain** [comment]
Still can't reproduce and lack of activity here, so I'm going to close this one now.
