### ISSUE TITLE
Green Bar when SSL/TLS

### ISSUE THREAD

**Issue by beli3ver** [vain/lariza#50]
Hello,

maybe I think it would be a create idea when the bar with URL become green or the https:// will become green and bold, when you have an encrypted connection to the website.

And maybe you could write the common name before the link, like this:

GITHUB, Inc | https://github.com

**Comment by vain** [comment]
Phew. This opens quite the can of worms, unfortunately.

What good is it to know that you're using SSL? It indicates that data is not transmitted as clear text. That's it. It does not indicate any of the following:

* Are you using strong ciphers?
* Is the CA which signed that particular certificate trustworthy?
* In other words, who can decrypt your data? Is it really the exact party that you have in mind?

It depends on *a lot* of things whether you can ignore those questions or not. For example, if you're in a hotel with open WiFi and some nasty guy in the other room hijacks/sniffs your connection, it's  probably good enough to know if you're using encryption or not. Or is it? What if the server is using terrible ciphers that could be broken by that guy?

I don't know if it's a good idea to tell users, hey, the bar is green because SSL is in use, you're good to go. I really want to avoid creating a false sense of security. (Right now, lariza doesn't tell you anything, which implies that, if you care a great deal about security, you should probably be using a different browser.)

A green bar only means that there's a better chance of you being "safe".

*If* we go for a green bar, we should also provide the following:

* An easy way to inspect the currently used certificate.
* An easy way to view the ciphers in use, and we should probably also "rate" them to tell users, "that's a good cipher and that one over there is not".
* An easy way to view and manipulate all CAs that are being used by your system.
* Probably an easier way to accept self-signed certificates (that's already possible, but a bit clunky).
* Maybe an option to pin certain certificates (which is very impractical if it's letsencrypt).
* We should care more about mixed content. (I'm not sure how WebKit handles that by default.)
* Probably more stuff that I haven't thought about, yet.

Maybe it would be easier to show a little hint if SSL is *not* in use. If you're using plain HTTP, you can be *sure* that others can read your data. The absence of that hint still wouldn't imply security, though ...

That's the can of worms.

(I hope I'm making sense here. It's a delicate subject and it's really easy to get lost in unrealistic scenarios.)

**Comment by beli3ver** [comment]
Ok, that's make really sense.
Maybe we could use something easy, like a open lock to show that you use http.

**Comment by beli3ver** [comment]
![lock_open](https://user-images.githubusercontent.com/7816755/26894274-31d8ab2a-4bbe-11e7-82f7-fa252a96f6db.png)

Like this one from here: http://www.famfamfam.com/lab/icons/silk/

**Comment by beli3ver** [comment]
Or, we can create a function that checks if for the url exists a https site and then open the https site:

```c
int webCheck(const char url[])
{
    return (system(strcat("wget --spider -q ", url)));
}

if(!webCheck("https://github.com"))
{
    printf("OK");
}
```

**Comment by vain** [comment]
I don't know. This doesn't feel right. All these hints are very likely to be misinterpreted. "Okay, there's no 'open lock', so I'm secure."

As I said above, a green (or red) bar alone doesn't solve the problem. There should be many other features as well.
